### PR TITLE
Fix undefined method each error occurring on static assets. [Fix #9]

### LINKED ISSUE #9: Having an issue getting rack-honeypot working
Hello!

I am using rails 3.2.9. I added `gem 'rack-honeypot' ` to my gemfile and ran bundler. I then added `config.middleware.use "Rack::Honeypot"` in envirnment.rb and got the following error:

```
NoMethodError (undefined method `each' for #<String:0x007fddfcd93b68>):
```

I also tried adding the config line to development.rb and application.rb. Both yielded the same results. Any ideas of what is happening?

Thank you.

### PR DESCRIPTION
**Pull request by JDutil**

### CODE REVIEW

**Comment by RandieM** [comment]
Hello everyone. Any news on this? Thanks!

**Comment by futhr** [comment]
+1

**Comment by JDutil** [comment]
@futhr if you want we could probably just push our own copy to spree-contrib organization and cut our own release since this doesn't appear to be going anywhere.

**Comment by futhr** [comment]
@JDutil :+1: since this has not been maintained for 3 years, rename it with _ underscore so it may be released to rubygems.

**Comment by revett** [comment]
**Please Merge** +1

**Comment by luigi** [comment]
Hi all, I left Sunlight Labs in 2012 and lost commit access. My apologies that this was left unattended. I've regained commit access for this repo, and will publish the gem update after getting myself set up for that again.

**Comment by revett** [comment]
@luigi thanks!

**Comment by JDutil** [comment]
:shipit:

**Comment by luigi** [comment]
Alrighty, version `0.1.3` is cut:

https://rubygems.org/gems/rack-honeypot

**Comment by futhr** [comment]
@luigi Thanks, and nice dedication :)

**Pull request merged**
